# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b01722439239a63e4cb9b95afab5ac6f41d229e565653d3882ff43d3beb203a2a6a02828077848f048fccbc342cda196fe48aa20b310026c3c432c7f56930a5c

test:
  secret_key_base: 05c411109f1c04b972de571a325dba62e19fa7bf4d78c8f8601997c7329db99ab57bc70970ef1113d26f6393c0836f6091f422008958c34d268885a98c36bae5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
